### ISSUE TITLE
[feat]: Overhaul the template

### ISSUE THREAD

**Issue by masaaldosey** [masaaldosey/cpp-template#1]
## General Description
The current template is a bit clunky and unnecessarily complicated. Need to strip down the redundant parts.

This will help in easier understanding of the C++ build system.

## TODOs
- [x] Use C++ _namespaces_.
- [x] Re-organize the `src` directory structure.
- [x] Break down the main `CMakeLists.txt` into hierarchical ones.
- [x] Add an `examples` directory which would demonstrate usage of the library.
- [x] Adapt CI workflow accordingly.

**Comment by masaaldosey** [comment]
All the above mentioned _TODOs_ have been resolved in this [commit](https://github.com/masaaldosey/cpp-template/tree/dd6d49adc18889ab21e64090a30ee4475cc5d688). 

Closing the issue. Will do it via Pull Requests from next time.
